### PR TITLE
 Add Docker Configuration for Frontend and Backend Services

### LINKED ISSUE #14: Add Dockerfile
Add Docker support to containerize both the frontend and backend services.

### Tasks:
- Create a Dockerfile for the frontend to build and serve the app.
- Create a Dockerfile for the backend to run the server.
- Set up docker-compose.yml for both services and networking.
- Test and ensure both containers work together.

### Acceptance Criteria:
- Dockerfiles and Docker Compose are added.
- Services run and communicate via docker-compose up.
- Documentation is updated.

### PR DESCRIPTION
**Pull request by vverma022**
### Description:

This PR adds Docker support for both the frontend (Vite) and backend (Node.js) services in the project. The Dockerfiles and docker-compose.yml are configured to streamline local development and deployment, enabling the services to run in isolated containers.

### Changes Introduced:

- Dockerfiles:
- Created a Dockerfile in the client folder for the frontend (Vite) application.
- Created a Dockerfile in the server folder for the backend (Node.js) application.
- Docker Compose Configuration:
- Added docker-compose.yml to manage both frontend and backend services.
- Configured services to run on:
- Frontend: Port 5173 for Vite development server.
- Backend: Dynamic port mapping using BACKEND_PORT from environment variables, with a default fallback to 3000.
- Both services are connected via a custom Docker network for internal communication.

### Notes:

- The backend is throwing an exception related to missing RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET. This error is unrelated to the Docker setup and should be addressed separately by configuring the necessary environment variables.

### How to Test:

1. Ensure Docker and Docker Compose are installed on your machine.
2. Run docker-compose up --build from the root directory.
3. Access the frontend via http://localhost:5173.
4. The backend should run on the port specified by BACKEND_PORT (default is 3000).

### CODE REVIEW

**Review by PorePranav — CHANGES_REQUESTED** [review]
Thank you for the PR introducing Dockerization with the Dockerfile and Docker Compose file. However, I noticed a few issues that need to be addressed:

1. **Environment Variables**: 
- Currently, the `.env` files are being added directly into the Docker image. It’s crucial to handle environment variables securely and avoid hardcoding sensitive information. Please ensure that these files are not included in the image and consider using a `.dockerignore` file to exclude them.

3. **Vite Configuration**: 
- There seems to be an issue with the Vite setup, causing a "The connection was reset" error. This could be related to how Vite's development server is configured within the container (e.g., port forwarding or incorrect binding to 0.0.0.0 instead of localhost).
- Could you look into adjusting the Vite server configuration to ensure it's correctly accessible, especially when running in the container?

Additionally, could you clarify whether you intend to set up the Dockerfile for a development or production environment? This will help in guiding any further configurations needed.

Once these changes are made, I believe the Docker setup will be more robust and functional. Let me know if you need any assistance with these adjustments!

**Comment by vverma022** [comment]
> Thank you for the PR introducing Dockerization with the Dockerfile and Docker Compose file. However, I noticed a few issues that need to be addressed:
> 
> 1. **Environment Variables**:
> 
> * Currently, the `.env` files are being added directly into the Docker image. It’s crucial to handle environment variables securely and avoid hardcoding sensitive information. Please ensure that these files are not included in the image and consider using a `.dockerignore` file to exclude them.
> 
> 3. **Vite Configuration**:
> 
> * There seems to be an issue with the Vite setup, causing a "The connection was reset" error. This could be related to how Vite's development server is configured within the container (e.g., port forwarding or incorrect binding to 0.0.0.0 instead of localhost).
> * Could you look into adjusting the Vite server configuration to ensure it's correctly accessible, especially when running in the container?
> 
> Additionally, could you clarify whether you intend to set up the Dockerfile for a development or production environment? This will help in guiding any further configurations needed.
> 
> Once these changes are made, I believe the Docker setup will be more robust and functional. Let me know if you need any assistance with these adjustments!

This for now will be for development so that users can easily setup the project and run locally.

**Review by PorePranav — CHANGES_REQUESTED** [review]
Thank you for submitting the PR and for your effort. However, I've noticed a few key issues:

1. **Environment Variable Handling**: As mentioned in the previous review, the environment variables are still not being managed properly. Please refer back to our initial conversation, and ensure that the variables are handled securely and correctly according to the project’s guidelines.

2. **Code Quality**: It appears that parts of the PR may have been generated or copied without proper context or testing. While it's okay to use external resources for inspiration, it is essential that the code integrates well with the existing system, is tested locally, and aligns with the project's requirements.

3. **Testing**: Please ensure that your changes are thoroughly tested locally before opening a PR. We aim to maintain a high standard of code quality, and this includes ensuring that all functionality works as expected.

Could you please make the necessary adjustments and test the code locally before resubmitting? I'd also recommend carefully reviewing our [contribution guidelines](https://github.com/PorePranav/CampusUnify/blob/main/CONTRIBUTING.md) to ensure your changes adhere to the project's best practices. For your reference I am attaching a screenshot below:

Screenshot 2024-10-07 194440


Looking forward to your updated PR!

**Comment by vverma022** [comment]
Thank you. And my apologies I'll make sure to update ensure everything works according

**Comment by vverma022** [comment]
Can you please let me know if changes are successful as I do not have access to razor-pay keys.

**Comment by PorePranav** [comment]
Thank you for submitting your PR and for your contributions to the project. Unfortunately, after reviewing it again, I have to let you know that it still does not meet the required standards despite the feedback provided earlier.

There are a number of things that still need improvement, and I have highlighted these in previous reviews. Given the current state of the PR, I will not be merging it at this time.

I understand you've put effort into this, but I'll need to make the necessary changes myself when I have the time to ensure the project maintains its quality and consistency.

Thank you for your understanding!

**Pull request closed without merging**
